-- PREMACHA CHAHA V3
-- Fresh Supabase SQL. This version has NO customer Udhaar system.

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 name text,email text,role text not null default 'staff' check(role in('owner','staff')),
 created_at timestamptz not null default now());

create table if not exists public.items(
 id bigint generated by default as identity primary key,name text not null,
 category text not null default 'Other',buy_price numeric(12,2) not null default 0,
 sell_price numeric(12,2) not null default 0,stock numeric(12,2) not null default 0,
 min_stock numeric(12,2) not null default 0,unit text not null default 'pcs',
 created_at timestamptz not null default now());

create table if not exists public.sales(
 id bigint generated by default as identity primary key,item_id bigint references public.items(id) on delete restrict,
 name text not null,qty numeric(12,2) not null,sell numeric(12,2) not null,buy numeric(12,2) not null,
 revenue numeric(12,2) not null,profit numeric(12,2) not null,
 payment text not null default 'Cash' check(payment in('Cash','UPI','Card')),
 date date not null default current_date,created_at timestamptz not null default now());

create table if not exists public.purchases(
 id bigint generated by default as identity primary key,item_id bigint references public.items(id) on delete restrict,
 name text not null,qty numeric(12,2) not null,price numeric(12,2) not null,total numeric(12,2) not null,
 supplier text,date date not null default current_date,created_at timestamptz not null default now());

create table if not exists public.expenses(
 id bigint generated by default as identity primary key,category text not null,
 amount numeric(12,2) not null,note text,date date not null default current_date,
 created_at timestamptz not null default now());

create table if not exists public.daily_closings(
 id bigint generated by default as identity primary key,
 date date unique not null,opening_cash numeric(12,2) not null default 0,
 cash_sales numeric(12,2) not null default 0,cash_expenses numeric(12,2) not null default 0,
 expected_cash numeric(12,2) not null default 0,actual_cash numeric(12,2) not null default 0,
 difference numeric(12,2) not null default 0,created_at timestamptz not null default now(),
 closed_by uuid references auth.users(id));

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,name,email,role) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),new.email,'staff') on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_owner() returns boolean language sql stable security definer set search_path=public as $$
select exists(select 1 from public.profiles where id=auth.uid() and role='owner'); $$;

alter table public.profiles enable row level security;
alter table public.items enable row level security;
alter table public.sales enable row level security;
alter table public.purchases enable row level security;
alter table public.expenses enable row level security;
alter table public.daily_closings enable row level security;

drop policy if exists "profile self or owner" on public.profiles;
drop policy if exists "owner update profiles" on public.profiles;
create policy "profile self or owner" on public.profiles for select to authenticated using(id=auth.uid() or public.is_owner());
create policy "owner update profiles" on public.profiles for update to authenticated using(public.is_owner()) with check(public.is_owner());

drop policy if exists "items signed in" on public.items;
drop policy if exists "items write staff" on public.items;
drop policy if exists "items update staff" on public.items;
create policy "items signed in" on public.items for select to authenticated using(true);
create policy "items write staff" on public.items for insert to authenticated with check(true);
create policy "items update staff" on public.items for update to authenticated using(true) with check(true);

drop policy if exists "sales signed in" on public.sales;
drop policy if exists "purchases signed in" on public.purchases;
drop policy if exists "expenses signed in" on public.expenses;
drop policy if exists "expenses insert" on public.expenses;
drop policy if exists "closing signed in" on public.daily_closings;
drop policy if exists "closing insert" on public.daily_closings;
create policy "sales signed in" on public.sales for select to authenticated using(true);
create policy "purchases signed in" on public.purchases for select to authenticated using(true);
create policy "expenses signed in" on public.expenses for select to authenticated using(true);
create policy "expenses insert" on public.expenses for insert to authenticated with check(true);
create policy "closing signed in" on public.daily_closings for select to authenticated using(true);
create policy "closing insert" on public.daily_closings for insert to authenticated with check(true);
create policy "closing update" on public.daily_closings for update to authenticated using(true) with check(true);

create or replace function public.record_sale(p_item_id bigint,p_qty numeric,p_date date,p_payment text)
returns void language plpgsql security definer set search_path=public as $$
declare x items%rowtype;
begin
select * into x from items where id=p_item_id for update;
if not found then raise exception 'Item not found'; end if;
if p_qty<=0 or x.stock<p_qty then raise exception 'Insufficient stock'; end if;
if p_payment not in('Cash','UPI','Card') then raise exception 'Invalid payment'; end if;
update items set stock=stock-p_qty where id=p_item_id;
insert into sales(item_id,name,qty,sell,buy,revenue,profit,payment,date)
values(x.id,x.name,p_qty,x.sell_price,x.buy_price,p_qty*x.sell_price,p_qty*(x.sell_price-x.buy_price),p_payment,p_date);
end $$;

create or replace function public.record_purchase(p_item_id bigint,p_qty numeric,p_price numeric,p_supplier text)
returns void language plpgsql security definer set search_path=public as $$
declare x items%rowtype;
begin
select * into x from items where id=p_item_id for update;
if not found then raise exception 'Item not found'; end if;
if p_qty<=0 or p_price<0 then raise exception 'Invalid purchase'; end if;
update items set stock=stock+p_qty,buy_price=p_price where id=p_item_id;
insert into purchases(item_id,name,qty,price,total,supplier,date)
values(x.id,x.name,p_qty,p_price,p_qty*p_price,p_supplier,current_date);
end $$;

grant execute on function public.record_sale(bigint,numeric,date,text) to authenticated;
grant execute on function public.record_purchase(bigint,numeric,numeric,text) to authenticated;

-- After creating the first Auth user, promote it:
-- update public.profiles set role='owner' where email='YOUR_OWNER_EMAIL';

-- Create the owner/staff accounts from Supabase Authentication > Users.
-- Public signup should be disabled for a private shop application.
